---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/with_apparmor/yaml-lint.yml
platforms:
  - name: "Instance - ${MOLECULE_DISTRO:-ubuntu16}"
    image: "kubecloudsas/docker-ansible-test:${MOLECULE_DISTRO:-ubuntu16}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
scenario:
  name: with_apparmor
verifier:
  name: testinfra
  lint:
    name: flake8
