---
# Get AppArmor parser version
- name: "({{ ansible_distribution }}) AppArmor::Config - Get AppArmor parser version"
  command: >
    apparmor_parser --version
    warn=no
  register: apparmor_parser_version
  changed_when: false
  failed_when: false
  check_mode: false

# Print Current AppArmor Parser version Check Raw result
- name: "({{ ansible_distribution }}) AppArmor::Config - Print Current AppArmor Parser version Check Raw result"
  debug:
    msg: "AppArmor installed : {{ apparmor_parser_version.rc == 0 }}"

# Set fact with AppArmor install status flag
- name: "({{ ansible_distribution }}) AppArmor::Config - Set fact with AppArmor install flag"
  set_fact:
    apparmor_installed: "{{ apparmor_parser_version.rc == 0 }}"

# Tasks block
- name: "({{ ansible_distribution }}) AppArmor::Config - Tasks block (Installed : {{ apparmor_parser_version.rc == 0 }})"
  block:

    # Ensure Old MySQL AppArmor config profile links are deleted
    - name: "({{ ansible_distribution }}) AppArmor::Config - Ensure Old MySQL AppArmor config profile links are deleted"
      file:
        path: "{{ item.link }}"
        state: absent
      loop: "{{ mysql_apparmor_config_path_link }}"
      changed_when: false
      failed_when: false
      check_mode: false

    # Ensure MySQL AppArmor config profile links are present
    - name: "({{ ansible_distribution }}) AppArmor::Config - Ensure MySQL AppArmor config profile links are present"
      file:
        src: "{{ item.src }}"
        dest: "{{ item.link }}"
        owner: "{{ apparmor_profile_user }}"
        group: "{{ apparmor_profile_group }}"
        state: link
      loop: "{{ mysql_apparmor_config_path_link }}"
      changed_when: false
      failed_when: false
      check_mode: false

    # Ensure AppArmor service restarted
    - name: "({{ ansible_distribution }}) AppArmor::Config - Reload AppArmor"
      service:
        name: "{{ apparmor_daemon }}"
        state: reloaded
      changed_when: false
      failed_when: false
      check_mode: false

  when: apparmor_installed|bool
