---

- name: "({{ ansible_distribution }}) MAIN::MySQL - Define mysql/maria service descriptor path"
  set_fact:
    mysql_service_descriptor_location: "/lib/systemd/system/mysql.service"
    maria_service_descriptor_location: "/usr/lib/systemd/system/mariadb.service"

- name: "({{ ansible_distribution }}) MAIN::MySQL - Check Mysql service file exists"
  stat:
    path: "{{ mysql_service_descriptor_location }}"
  register: mysql_service_file_stat

- name: "({{ ansible_distribution }}) MAIN::MySQL - Check MariaDB service file exists"
  stat:
    path: "{{ maria_service_descriptor_location }}"
  register: maria_service_file_stat

- name: "({{ ansible_distribution }}) MAIN::MySQL - Check MySQL default data dir exists"
  stat:
    path: "{{ mysql_default_datadir }}"
  register: mysql_default_datadir_exists_result

- name: "({{ ansible_distribution }}) MAIN::MySQL - Get MySQL default data dir content"
  find:
    paths: "{{ mysql_default_datadir }}"
    patterns: "*"
  register: mysql_default_datadir_content_result

- name: "({{ ansible_distribution }}) MAIN::AppArmor - Check AppArmor MySQL Configuration"
  stat:
    path: "{{ mysql_apparmor_profile_config }}"
  register: apparmor_mysql_profile_exists_result

- name: "({{ ansible_distribution }}) MAIN::AppArmor - Check AppArmor Service is installed"
  shell:
  args:
    cmd: "service {{ apparmor_daemon }} status"
    warn: false
  changed_when: false
  failed_when: false
  check_mode: false
  register: apparmor_service_installed_result

- name: "({{ ansible_distribution }}) MAIN::MySQL - Define commons facts"
  set_fact:
    mysql_install_packages: "{{ (rh_mysql_install_packages is defined and rh_mysql_install_packages.changed)
      or (deb_mysql_install_packages is defined and deb_mysql_install_packages.changed)
      or (arch_mysql_install_packages is defined and arch_mysql_install_packages.changed) }}"
    apparmor_mysql_profile_installed: "{{ apparmor_mysql_profile_exists_result.stat.exists == true }}"
    apparmor_installed: "{{ apparmor_service_installed_result.rc == 0 }}"
    mysql_default_datadir_installed: "{{ mysql_default_datadir_exists_result.stat.exists == true }}"
    mysql_default_datadir_not_empty: "{{ mysql_default_datadir_content_result.matched > 0 }}"

- name: "({{ ansible_distribution }}) MySQL::Config - Generate mysql service file."
  template:
    src: mysql.service.j2
    dest: "{{ mysql_service_descriptor_location }}"
    owner: root
    group: root
    mode: 0644
    force: true
  when:
    - mysql_service_file_stat.stat.exists | bool
  tags:
    - molecule-idempotence-notest
  notify: daemon-reload mysql

- name: "({{ ansible_distribution }}) MySQL::Config - Generate mariadb service file."
  template:
    src: maria.service.j2
    dest: "{{ maria_service_descriptor_location }}"
    owner: root
    group: root
    mode: 0644
    force: true
  when:
    - maria_service_file_stat.stat.exists | bool
  tags:
    - molecule-idempotence-notest
  notify: daemon-reload mysql
