---
# Variable configuration.
- include_tasks: variables.yml

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- include_tasks: initialize-commons-facts.yml

# Configure MySQL Default.
- name: "({{ ansible_distribution }}) MAIN::Include - Configure MySQL with default 'DataDir'"
  include_tasks: configure-default-mysql.yml
  when:
    - mysql_default_datadir == mysql_datadir

# Configure MySQL With Change Dirs.
- name: "({{ ansible_distribution }}) MAIN::Include - Configure MySQL with Custom 'DataDir'"
  include_tasks: configure-custom-mysql.yml
  when:
    - mysql_default_datadir != mysql_datadir

# Configure MySQL.
- include_tasks: secure-installation.yml
- include_tasks: databases.yml
- include_tasks: users.yml
- include_tasks: replication.yml
