---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: ansible-role-mysql

  pre_tasks:

    - name: "Set discovered Ansible Python interpreter."
      set_fact:
        ansible_python_interpreter: "{{ ansible_facts.python.executable }}"
      when: ansible_python_interpreter is not defined

   - name: "Show Python intrpreter"
     debug:
      msg: "Python Interpreter : {{ ansible_python_interpreter }}"

  post_tasks:
    - name: Make sure we can connect to MySQL via Unix socket.
      command: "mysql -u root -proot -e 'show databases;'"
      changed_when: false

    - name: Make sure we can connect to MySQL via TCP.
      command: "mysql -u root -proot -h 127.0.0.1 -e 'show databases;'"
      changed_when: false
